### ISSUE TITLE
CS0534	'MonkeyContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'

### ISSUE THREAD

**Issue by ShamilS** [dotnet-presentations/blazor-hybrid-workshop#1]
The subject issue happens when working through `Part 1 - Displaying Data`:
  
" *Add this also in the Monkey.cs under the Monkey class.*

    // This using statement needs to go in the top of the Monkey.cs file
    using System.Text.Json.Serialization;
    ...    
    // Make sure that this is outside of the Monkey class
    [JsonSerializable(typeof(List<Monkey>))]
    internal sealed partial class MonkeyContext : JsonSerializerContext
    {
    
    }
"

The resolution for me was to clean the solution, close and reopen it, then rebuild it.

Still the open question is: "Why the subject issue happens?"

**Comment by jfversluis** [comment]
Probably due to a hiccup in Visual Studio or some process that was not completed yet. I think that uses source generators, to maybe some code wasn't generated correctly (yet).

Sorry this happened, but I don't think this should happen much more often nor is there much we can do about it on our side.
